development:
  adapter: mysql2
  encoding: utf8
  database: myapp_development
  username: root
  pool: 5
test:
  adapter: mysql2
  encoding: utf8
  database: myapp_test
  username: root
  pool: 5
production:
  url: <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
