# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f566cd4fe5cb71a76bb98224874d70c2fb5484fc5ebcb04612596ef156fa64dc42f9d983ac2e39eae0260a68f19018150a934d40e2cba0b41d803cf356d6157f
  bittrex_key: <%= ENV["KEY"] %>
  bittrex_secret: <%= ENV["SECRET"] %>

test:
  secret_key_base: 73a8d88525bb75487abdc5a64c3fa3b7dd3d3bbdb324150184ff174dd9fe24d2ec6997de5e2fe904ab403548927524afe7e844cb5d8939bca7a34cdb9b385731

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bittrex_key: <%= ENV["KEY"] %>
  bittrex_secret: <%= ENV["SECRET"] %>
